#!/usr/bin/perl
#
# runNuclDyn: launcher for Nucl. Dynamics executables
# Josep Ll. Gelpi 2018
# Marc del Pino 2019
use strict;
use File::Basename;
use Cwd;

my $RSCRIPT = "/usr/bin/Rscript";
my $NDDIR = "/home/NucleosomeDynamics";

if (! -d $NDDIR){
	my $lo = dirname($0);
	$lo =~ s/\.//g;
	$NDDIR = cwd().$lo;
}

my $BINDIR = "$NDDIR/NuclDyn/bin";
my $STATSDIR = "$NDDIR/NuclDyn/statistics";
my $HELPDIR = "$NDDIR/help";

my $DATADIR = "/data_dir";     # used to find DATADIR/scripts/user_wf.file
my $PUBLICDIR = "/public_dir"; # OBSOLETE

my $FUNCTIONS = ['run','readBAM','nucleR','NFR','txstart','periodicity','stiffness','nucDyn','nucleR2structure','toBigWig','fromBigWig','coverage','js_plot'];
my $FUNCTIONS_STATS = ['nucleR_stats','NFR_stats','txstart_stats','periodicity_stats','stiffness_stats','nucDyn_stats'];

#
system ("/bin/cat $HELPDIR/header.txt");

# Main Help

if (!@ARGV || ($ARGV[0] eq '--help') || ($ARGV[0] eq '-h')) {
    system ("/bin/cat $HELPDIR/main.hlp");
    exit;
}

my $op = shift;

if (!is_valid_function($op) && !is_valid_function_stats($op)) {
    die "\nError: unrecognized function $op, try [-h |--help]\n\n";
}

#Specific help
if (!@ARGV || ($ARGV[0] eq '--help') || ($ARGV[0] eq '-h')) {
    system ("/bin/cat $HELPDIR/$op.hlp");
    exit;
}

# Running tool
#
if (-e $DATADIR) {
    chdir $DATADIR;
}

if ($op eq "run") {
    print "===> Running $op <===\n\n";
    system ("/bin/sh $DATADIR/scripts/$ARGV[0]");
} else {
    print "===> Running $op <===\n\n";
    if (($op =~ /stats/) && is_valid_function_stats($op)) {
	$op =~ s/_stats//g;
        my $args_str = join(" ",@ARGV);
        print "$RSCRIPT $STATSDIR/$op.R $args_str\n";
        system ("$RSCRIPT $STATSDIR/$op.R ". join " ",@ARGV);
    } elsif (is_valid_function($op)) {
        my $args_str = join(" ",@ARGV);
        print "$RSCRIPT $BINDIR/$op.R $args_str\n";
        system ("$RSCRIPT $BINDIR/$op.R ". join " ",@ARGV);
    } else {
        system ("/bin/cat $HELPDIR/main.hlp");
    }
}

sub is_valid_function {
   my $f = shift;
   return _is_valid($f, $FUNCTIONS);
}

sub is_valid_function_stats {
   my $f = shift;
   return _is_valid($f, $FUNCTIONS_STATS);
}

sub _is_valid {
  my ($f, $list) = @_;
  my $i=0;
  
  while (($i<$#{$list}) && ($list->[$i] ne $f)) {$i++};
  return ($list->[$i] eq $f);
}
   
