source("https://bioconductor.org/biocLite.R")
biocLite('dplyr')
biocLite('IRanges')
biocLite('GenomicRanges')
biocLite('ShortRead',ask = FALSE)
biocLite('doParallel')
biocLite('ggplot2')
biocLite('magrittr')
